name: Dependent jobs

on: [push]

jobs:
  run-ubuntu-latest-1:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Onur"
      - name: multiple line script
        run: |
          npm -v
          node -v
  run-ubuntu-latest-2:
    runs-on: ubuntu-latest
    needs: ["run-ubuntu-latest-1"]
    steps:
      - name: echo string
        run: echo "Onur"
      - name: multiple line script
        run: |
          npm -v
          node -v