name: Simple Javascript Action

on: [push]

jobs:
  job-name-here:
    runs-on: ubuntu-latest
    steps:
      - name: Javascript Action
        id: greet
        uses: actions/hello-worl-javascript-action@v1
        with:
          who-to-greet: Onur #who-to-greet taken from the actions library itself. its just a parametre that action creators declared
      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"