name: workflow name

on: [push]

jobs:
  job-name-here:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world"
      - name: multi line script
        run: |
          node -v
          npm -v
